#!/usr/bin/env node
/**
 * One-time content seed: pushes the real transcribed copy from src/lib/content.ts (SEED_*)
 * into a freshly-created Sanity dataset, uploading the local images along the way, so the
 * author starts editing from real content instead of an empty Studio.
 *
 * Usage (from the site/ directory, after `npm install` and setting up .env.local — see
 * .env.local.example):
 *   node --env-file=.env.local scripts/seed-sanity.mjs
 *
 * Requires SANITY_API_TOKEN with **write** access (Sanity dashboard → API → Tokens → Add API
 * token → Editor). Safe to re-run: projects/skills are matched by slug/name and updated in
 * place (createOrReplace) rather than duplicated; images are only re-uploaded if missing.
 */
import { createClient } from "@sanity/client";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(__dirname, "..", "public");

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET;
const token = process.env.SANITY_API_TOKEN;

if (!projectId || !dataset || !token) {
  console.error(
    "Missing env vars. Need NEXT_PUBLIC_SANITY_PROJECT_ID, NEXT_PUBLIC_SANITY_DATASET, SANITY_API_TOKEN " +
      "(a write-access token from the Sanity dashboard). See .env.local.example."
  );
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: "2026-01-01",
  token,
  useCdn: false,
});

async function uploadImage(publicPath) {
  const abs = path.join(publicDir, publicPath.replace(/^\//, ""));
  const buffer = await readFile(abs);
  const asset = await client.assets.upload("image", buffer, { filename: path.basename(abs) });
  return { _type: "image", asset: { _type: "reference", _ref: asset._id } };
}

async function main() {
  // Import content.ts's TS source via a quick regex-free approach isn't possible directly in
  // plain Node (it's TypeScript) — instead we re-declare the same data by importing the compiled
  // seed JSON generated by scripts/export-seed.mjs. Simplest robust path: shell out to that
  // helper first if the JSON doesn't exist yet.
  const seedJsonPath = path.join(__dirname, "seed-data.generated.json");
  let seed;
  try {
    seed = JSON.parse(await readFile(seedJsonPath, "utf8"));
  } catch {
    console.error(
      `${seedJsonPath} not found. Run \`npm run export-seed\` first (compiles the TS seed data to JSON), then re-run this script.`
    );
    process.exit(1);
  }

  console.log(`Seeding project ${projectId}/${dataset}...`);

  console.log(`\nUploading ${seed.projects.length} project cover images...`);
  const imageCache = new Map();
  async function cachedUpload(p) {
    if (!imageCache.has(p)) imageCache.set(p, await uploadImage(p));
    return imageCache.get(p);
  }

  for (const [i, p] of seed.projects.entries()) {
    const cover = await cachedUpload(p.image);
    await client.createOrReplace({
      _id: `project-${p.slug}`,
      _type: "project",
      title: p.title,
      slug: { _type: "slug", current: p.slug },
      tech: p.tech,
      year: p.year,
      cover,
      role: p.role,
      body: p.body,
      tasks: p.tasks,
      result: p.result,
      order: Number(p.index),
      titleEn: p.titleEn,
      roleEn: p.roleEn,
      bodyEn: p.bodyEn,
      tasksEn: p.tasksEn,
      resultEn: p.resultEn,
    });
    console.log(`  [${i + 1}/${seed.projects.length}] ${p.slug}`);
  }

  console.log(`\nCreating ${seed.skills.length} skills...`);
  for (const s of seed.skills) {
    await client.createOrReplace({
      _id: `skill-${s.name.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}`,
      _type: "skill",
      name: s.name,
      level: s.level,
      body: s.body,
      bodyEn: s.bodyEn,
    });
  }

  console.log("\nCreating siteSettings singleton...");
  const portrait = await cachedUpload(seed.site.about.portrait);
  await client.createOrReplace({
    _id: "siteSettings",
    _type: "siteSettings",
    name: seed.site.name,
    role: seed.site.role,
    heroSpecs: seed.site.heroSpecs,
    aboutTitle: seed.site.about.title,
    aboutLede: seed.site.about.lede,
    aboutBody1: seed.site.about.body1,
    aboutBody2: seed.site.about.body2,
    aboutPortrait: portrait,
    aboutMeta: seed.site.about.meta,
    workLede: seed.site.work.lede,
    skillsEmptyState: seed.site.skills.emptyState,
    contactTitle: seed.site.contact.title,
    contactRows: seed.site.contact.rows,
    heroSpecsEn: seed.site.heroSpecsEn,
    aboutTitleEn: seed.site.about.titleEn,
    aboutLedeEn: seed.site.about.ledeEn,
    aboutBody1En: seed.site.about.body1En,
    aboutBody2En: seed.site.about.body2En,
    aboutMetaEn: seed.site.about.metaEn,
    workLedeEn: seed.site.workLedeEn,
    skillsEmptyStateEn: seed.site.skillsEmptyStateEn,
    contactTitleEn: seed.site.contactTitleEn,
  });

  console.log("\nDone. Open /studio on your site (or https://" + projectId + ".sanity.studio once deployed) to see it.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
